version: "3"

services:
  libretranslate:
    container_name: libretranslate
    hostname: libretranslate
    build:
      context: ./LibreTranslate/LibreTranslate
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      LT_DISABLE_WEB_UI: true
    expose:
      - "5000"
    ports:
      - "5000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    volumes:
      - "./LibreTranslate/LibreTranslateModels/share:/home/libretranslate/.local/share"
      - "./LibreTranslate/LibreTranslateModels/cache:/home/libretranslate/.local/cache"
      

  # backend:
  #   container_name: backend
  #   build: 
  #     context: WordWanderBackend/
  #     dockerfile: Dockerfile
  #   # environment:
  #     # "ASPNETCORE_ENVIRONMENT": "Development"
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - "./WordWanderBackend/appsettings.json:/app/appsettings.json"
  #     - "./BookStorage:/books"
  

  database:
    container_name: postgres
    hostname: database_host
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:15-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "./DBData:/var/lib/postgresql/data"
    
      

